### PR TITLE
Added Full Documentation required for flask

### LINKED ISSUE #171: Documentation required for the project
Some changes are required since its migrated to flask we have to add a documentation to read me

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issue 

Added Full Documentation required for flask

Closes: #171 

### Describe the changes you've made

I will upload  a video for this

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Additional Info (optional)
Any additional information you want to give

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/117985894-bdee4300-b356-11eb-8b75-ba72592c7024.mp4

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/117985894-bdee4300-b356-11eb-8b75-ba72592c7024.mp4

**Comment by arpit456jain** [comment]
https://github.com/arpit456jain/pixelvibe/tree/docs

You can view the documentation on this branch 👆

**Comment by adarshvulli** [comment]
@arpit456jain, this is excellent work on the documentation part! But I suggest instead of disturbing the present, read me add the flask set up setups over the contribution.MD or modify it accordingly; I hope you got my point

**Comment by adarshvulli** [comment]
Over the readme, we add a separate section called initial setup then redirect it to separate or detailed steps. This would look better

**Comment by arpit456jain** [comment]
> Over the readme, we add a separate section called initial setup then redirect it to separate or detailed steps. This would look better

Ok no problem .
Most of the project on which i had worked they had the set up in their read me that's why i add it there . Since it is looking nice in read me . If i add these in a separate file it will look like a boring documentation.

Rest decision is all yours i will do as you want

**Comment by adarshvulli** [comment]
yeah, I agree! let me get back to you regarding the same if possible; just try to make the separate file we can redirect. If not, we can leave the readme concerning the pr you made :)

**Comment by arpit456jain** [comment]
I suggest to merge this for now so that new contributors doesn't find any problem 
If any changes required i am always here 
@adarshvulli @ankitapuri

**Comment by ankitapuri** [comment]
> yeah, I agree! let me get back to you regarding the same if possible; just try to make the separate file we can redirect. If not, we can leave the readme concerning the pr you made :)

Most of them have it within the readme so its fine

**Pull request merged**
