### PR TITLE
Logout Feature is added

### LINKED ISSUE #189: Logout feature for user
Currently there is no Logout feature for user .
I will add the backend for logout and 

I will also take care when user is login , on home page it will show logout and if its not log in then it will show login/signup
on navbar

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issue 

Logout Feature is added

Closes: #189 

### Describe the changes you've made

https://user-images.githubusercontent.com/55352601/118376091-7d572980-b5e3-11eb-8905-d46358551e2a.mp4

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Additional Info (optional)
Any additional information you want to give

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by arpit456jain** [comment]
@adarshvulli please review this PR its the last part of backend .
backend is completed now :) 

@ankitapuri please have a look

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/118402903-95818400-b689-11eb-900c-bdb6e4a19afb.mp4

**Review by adarshvulli — APPROVED** [review]
@ankitapuri this works fine! good to be merged, @arpit456jain great work

**Comment by ankitapuri** [comment]
@arpit456jain please resolve it once

**Pull request merged**
