### PR TITLE
Migration to Flask

### LINKED ISSUE #167: Migration to flask
I have migrated whole website to flask and separate that one index.html page to two pages one is user_input and the other one is canvas.html

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issue 

I have migrated whole website to flask and separate that one index.html page to two pages one is user_input and the other one is canvas.html

Closes: #167 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Additional Info (optional)
Any additional information you want to give

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by arpit456jain** [comment]
Just open the terminal in folder where app.py is present and run the command
Py.exe app.py

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/117702654-692bba80-b1e6-11eb-9a73-ad0b22c9f747.mp4

**Comment by arpit456jain** [comment]
@adarshvulli can you please review my PR and check whether all features are working well or not

**Comment by adarshvulli** [comment]
Hey, @arpit456jain, this is great work, but there are conflicts due to the recent merge of the card! It's okay; try to rectify it! then we are good to be merged

**Comment by arpit456jain** [comment]
> Hey, @arpit456jain, this is great work, but there are conflicts due to the recent merge of the card! It's okay; try to rectify it! then we are good to be merged

Hey @adarshvulli @ankitapuri Resolved the merge conflicts , Good to go From my side

**Review by ankitapuri — APPROVED** [review]

**Pull request merged**
