### PR TITLE
added new features in canvas.html file

### LINKED ISSUE #128: Adding new feature
@ankitapuri  I would like to add different sized pens.

### PR DESCRIPTION
**Pull request by subhangi2731**
## Related Issue 
Added new features in canvas.html file and modified it

- Info about the related issue 

Closes: #128 

### Describe the changes you've made
 A drop down menu and also the variable brush sizes to be appeared in some drop side ways fashion thus adding new features

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
NA

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by ankitapuri — CHANGES_REQUESTED** [review]
image
Please delete the 2 brushes , and add the one u have added on the top

**Comment by subhangi2731** [comment]
@ankitapuri we have to use that brush by selecting if I delete then how the size will be selected?? can u please explain in detail exactly what u want

**Comment by ankitapuri** [comment]
> @ankitapuri we have to use that brush by selecting if I delete then how the size will be selected?? can u please explain in detail exactly what u want

At first the user gets the default size brush , and u have made the feature to change the brush-size. 
So just merge these 2 features into 1 , i.e. when user can use the brush of preferred size by selecting your feature

**Comment by subhangi2731** [comment]
@ankitapuri the thing which u are telling I have done that only.. The default is the smallest dot which is the current brush size but if we select larger dots only then the new size will be selected

**Comment by arpit456jain** [comment]
> @ankitapuri the thing which u are telling I have done that only.. The default is the smallest dot which is the current brush size but if we select larger dots only then the new size will be selected

@subhangi2731 i think @ankitapuri is trying to say that currently there are 2 options in drop down 1 is brush and 1 is brush size . 
If i user eraser and then i increased the brush size. And when i go back on page it still on eraser mode . I mean for using brush i have to select brush option first ..

So if you combine those 2 options that would be better. We can select and change size with the same

**Comment by arpit456jain** [comment]
like this
@ankitapuri like this ??

**Comment by subhangi2731** [comment]
@arpit456jain I got it I got the point thanks I will resolve now

**Comment by subhangi2731** [comment]
@ankitapuri please merge my pr I have done the required changes as said

**Comment by subhangi2731** [comment]
and updated my branch

**Comment by ankitapuri** [comment]
https://user-images.githubusercontent.com/54734002/119375335-516d2f80-bcd8-11eb-9f5f-e16e92b1fd89.mp4

@subhangi2731  the eraser size still changes with the brush size . It should be of the default size throughout

**Comment by subhangi2731** [comment]
@ankitapuri please check now and merge

**Comment by ankitapuri** [comment]
@subhangi2731 it has same errors , can u please send the video of the functionality .

**Comment by subhangi2731** [comment]
@ankitapuri Since erasing uses the same logic as brushing but with a white color, we have to click on erase again after changing the size of brush. Since I added the functionality already this must be handled in another issue
please consider and merge my pr I request you

**Comment by subhangi2731** [comment]
https://user-images.githubusercontent.com/53938490/119518679-5f818580-bd96-11eb-8959-63e5c1d0c335.mp4

**Review by ankitapuri — APPROVED** [review]

**Pull request merged**
