### PR TITLE
Updated index.html and style.css to add background . 

### PR DESCRIPTION
**Pull request by BharatiSukanya**
I updated to showcase a pure CSS Animated Gradient Background for the website. The color keeps changing dynamically on its own and a mixture of colors is present.
@ankitapuri  Have a look at it and let me know what do you think of it?

### CODE REVIEW

**Comment by ankitapuri** [comment]
Please provide a description related to your PR and also join Gitter chat .

**Comment by BharatiSukanya** [comment]
The style.css & index.html files have been updated  to showcase a pure CSS Animated Gradient Background for the website.
The color keeps changing dynamically  on its own and a mixture of colors is present.

The code added is as follows:

1. STYLE.CSS
(body tag & keyframe which describes the animation behavior)

body {
	background: linear-gradient(-45deg, #ee7752, #e73c7e, #23a6d5, #23d5ab);
	background-size: 400% 400%;
	animation: gradient 15s ease infinite;
}

@keyframes gradient {
	0% {
		background-position: 0% 50%;
	}
	50% {
		background-position: 100% 50%;
	}
	100% {
		background-position: 0% 50%;
	}
}

2.INDEX.HTML
(The src attribute specifies the URL of an external script file used here)

<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" integrity="sha256-qM7QTJSlvtPSxVRjVWNM2OfTAz/3k5ovHOKmKXuYMO4=" crossorigin="anonymous"></script>

**Comment by ankitapuri** [comment]
Yeah I have seen the effects . @BreadGenie can you also review it once.

**Review by BreadGenie — CHANGES_REQUESTED** [review]
Looks great but it doesn't match well with the design of home page refer #9 
you can go with the color scheme of homepage or discuss with the team again and pick one

**Comment by BharatiSukanya** [comment]
Sure @BreadGenie I will look into it again and come up with a better background. Thank you

**Pull request closed without merging**
