### PR TITLE
Grid shows when you click on submit button

### PR DESCRIPTION
**Pull request by micksharma**
## Related Issue 

- Info about the related issue 

Closes: #[issue number that will be closed through this PR]

### Describe the changes you've made

Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Additional Info (optional)
Any additional information you want to give

## Checklist:

- [x] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by ankitapuri** [comment]
U just added one line comment . No change in the functionality

**Comment by micksharma** [comment]
I make little bit attractive but it works when you click on submit button it shows grid.

**Comment by ankitapuri** [comment]
> I make little bit attractive but it works when you click on submit button it shows grid.

Its not showing on online servers . In local machine it works perfectly

**Comment by adarshvulli** [comment]
sir I don't see much of the changes u made !  no functionality is added or improvised!

**Pull request closed without merging**
