### PR TITLE
show Password in Password Reset Page and make code re useable

### LINKED ISSUE #308: show Password in Password Reset Page and make code re useable
show Password in Password Reset Page and make code re useable

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issue 

show Password in Password Reset Page and make code re useable

Closes: #308 

### Describe the changes you've made

Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Additional Info (optional)
Any additional information you want to give

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by arpit456jain** [comment]
@ankitapuri in  this PR i added show password in reset password 
and i created a separate file for show password js so that we can use this feature any where , any time very easily

**Comment by arpit456jain** [comment]
@adarshvulli kindly review

**Comment by adarshvulli** [comment]
image
@arpit456jain Once check, view password is not mapped in the sign in page

**Comment by arpit456jain** [comment]
@adarshvulli Check now its fixed

**Review by adarshvulli — APPROVED** [review]

**Pull request merged**
