### PR TITLE
added validations in signup

### LINKED ISSUE #265: validations in sign up
validations in sign up

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issue 

added validations in signup

Closes: #265 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Additional Info (optional)
Any additional information you want to give

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/119261776-80ab7000-bbf6-11eb-86b1-3bfd61b62b0f.mp4

**Comment by arpit456jain** [comment]
@ankitapuri please review this PR

**Comment by ankitapuri** [comment]
> @ankitapuri please review this PR

To make the password more secure , you can add special characters too

**Comment by arpit456jain** [comment]
> > @ankitapuri please review this PR
> 
> To make the password more secure , you can add special characters too

@ankitapuri don't worry of that i will add some good validations in front end . In this PR I just. Added nesscary validation so that no error will occur

**Pull request merged**
