### PR TITLE
Added Preloader

### LINKED ISSUE #125: [Preloader]
Hey @ankitapuri ,
I would like to add a animated PRELOADER to the website. Please assign this to me

### PR DESCRIPTION
**Pull request by archanagandhi**
Closes: #125 

## Describe the changes you've made
Added a new ***Preloader*** feature with animation effect

## Give a clear description what modifications you have made
Modified the ```index.html```  ```style.css``` and ```app.js``` file to build a animated preloader

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code
NA
## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by ankitapuri** [comment]
Its great @archanagandhi  , but can u match the colors of the background and loader . You can choose some good combination 
like #f57b70 and #b1a1ff or any of your choice

**Comment by archanagandhi** [comment]
I couldn't get you @ankitapuri , Which background and loader? Can u please tell which color should be changed?

**Comment by ankitapuri** [comment]
see when the pre-loader ends , we immediately get a page whose color changes to so much extreme and it doesn't suit the color of the pre-loader . so I was talking to change some color combination

**Comment by archanagandhi** [comment]
https://user-images.githubusercontent.com/74424757/115192357-51da3f80-a108-11eb-8984-fb276b814851.mp4

How about this? Tried the logo color combination.

**Comment by ankitapuri** [comment]
>  modified.color.mp4 
> How about this? Tried the logo color combination.

cool

**Comment by rish-singhal** [comment]
Not sure why, but it doesn't seem to work well, it usually takes a lot of time before the loader appears (in chrome).

although in Safari, it doesn't load at all (there is a black screen).

can you guys confirm? @ankitapuri @avinal

**Comment by ankitapuri** [comment]
> Not sure why, but it doesn't seem to work well, it usually takes a lot of time before the loader appears (in chrome).
> 
> although in Safari, it doesn't load at all (there is a black screen).
> 
> can you guys confirm? @ankitapuri @avinal

I don't have idea about Safari , but for me Chrome is fine

**Comment by avinal** [comment]
> Not sure why, but it doesn't seem to work well, it usually takes a lot of time before the loader appears (in chrome).
> 
> although in Safari, it doesn't load at all (there is a black screen).
> 
> can you guys confirm? @ankitapuri @avinal

It does take some time to appear, except that it is working fine in both chrome and firefox

**Review by avinal — COMMENTED** [review]
> Not sure why, but it doesn't seem to work well, it usually takes a lot of time before the loader appears (in chrome).
> 
> although in Safari, it doesn't load at all (there is a black screen).
> 
> can you guys confirm? @ankitapuri @avinal

It does take some time to appear, except that it is working fine in both chrome and firefox

**Comment by archanagandhi** [comment]
@rish-singhal @avinal For me it works completely fine in Chrome as well as Firefox. Could you please share a video of what you're facing?

**Comment by archanagandhi** [comment]
https://user-images.githubusercontent.com/74424757/115330661-26139400-a1b2-11eb-99a3-9c8be03cc13c.mp4

You can have a look at this. As soon as I click enter preloader appears.

**Comment by rish-singhal** [comment]
Seems to work fine now. @avinal @ankitapuri  let's merge?

**Review by rish-singhal — APPROVED** [review]

**Comment by ankitapuri** [comment]
> Seems to work fine now. @avinal @ankitapuri let's merge?

Is it now working fine in Safari @rish-singhal

**Comment by rish-singhal** [comment]
Yes

**Pull request merged**
