### PR TITLE
Animation added

### PR DESCRIPTION
**Pull request by RaveenaBhasin**
Added an infinite heartbeat animation in the PixelVibe headline using css to make it more attractive.

### CODE REVIEW

**Comment by ankitapuri** [comment]
You can't create a new file of your own , Need to edit in the existing index.html

**Comment by RaveenaBhasin** [comment]
Ok Ma'am I'll do the operation on the existing file

**Comment by RaveenaBhasin** [comment]
I have added one text animation in index.html .
Please have a look at it.

**Comment by arpit456jain** [comment]
@ankitapuri please close this PR

**Pull request closed without merging**
