### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ankitapuri**

### CODE REVIEW

**Comment by BreadGenie** [comment]
Looks great!
@ankitapuri you can merge the PR!

**Comment by anandbaburajan** [comment]
@ankitapuri I think you've mentioned steps on 'how to contribute' under 'setup' which isn't the right way. For example, users won't need to create a branch or commit changes if they wish to  just 'setup' and try out your project, right? You can take a look at https://github.com/FOSS-Cell-GECPKD/Hide-it if you need any ideas

**Comment by anandbaburajan** [comment]
@ankitapuri You don't need to close the PR. You can just edit the file and push new changes (commits)

**Comment by ankitapuri** [comment]
Yeah I have mentioned those steps

**Comment by ankitapuri** [comment]
> @ankitapuri You don't need to close the PR. You can just edit the file and push new changes (commits)

Okay!! Actually I had to change the brach name so need to close the previous one .

**Pull request closed without merging**
