### PR TITLE
added pencil cursor for canvas

### LINKED ISSUE #159: Custom Pencil Cursor instead of Crosshair for the Canvas
## Link to Cursor demo
https://custom-cursor.com/en/collection/life-style/pencil

If you like this idea, I would love to add a custom pencil cursor exactly like the demo one

### PR DESCRIPTION
**Pull request by N-Shar-ma**
## Type of change

What sort of change have you made:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
NA

## Checklist:
- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly whereever it was hard to understand.
- [X] My changes generate no new warnings.
- [X] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by avinal — COMMENTED** [review]
Hello @N-Shar-ma,
image
As you can see this is still crosshair. Also, I will suggest not to use some web URL to show pencil, find some alternative, like a font file or icon file.

**Comment by N-Shar-ma** [comment]
@avinal, that url is a data url, not web url, so it won't ever happen that the link becomes broken. I used a data url instead of a file path since it means 1 less http request, which makes the site faster. However, if you still want me to use a local svg file instead, I can do that too.

Also, please re-review, the cursor should appear as expected now

**Comment by ankitapuri** [comment]
Can u please share the screen recording of ur code been implementing . Its easy to review

**Comment by N-Shar-ma** [comment]
https://user-images.githubusercontent.com/68962290/118356748-62a99400-b594-11eb-9597-c82c9459dbd3.mp4

@ankitapuri

**Review by avinal — APPROVED** [review]
image
Hello @N-Shar-ma, sorry for being late, but the addition seems to work fine in my test(I created an abstract art too 😅 ), It may be merged if no further review is required @ankitapuri

**Comment by N-Shar-ma** [comment]
@avinal it's alright, thank you!

**Pull request merged**
