### PR TITLE
removed unnessacary css and added proper comments

### LINKED ISSUE #210: Cleaning of canvas.html and adding proper comments to css and js
Cleaning of canvas.html required since there is lots of unnecessary CSS and js  and adding proper comments to css and js

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issue 

Cleaning of canvas.html required since there is lots of unnecessary CSS and js and adding proper comments to css and js

Closes: #210 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Additional Info (optional)
Any additional information you want to give

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by arpit456jain** [comment]
@adarshvulli kindly review this PR . Whether all the features are working well or not .
I had added some bootstrap classes and removed hard-coded css and moved all internal css to a separate file

**Comment by adarshvulli** [comment]
> @adarshvulli kindly review this PR whether all the features are working well or not.
> I had added some bootstrap classes and removed hard-coded CSS, and moved all internal CSS to a separate file

image
hey @arpit456jain, everything works fine if possible, just add  a space or try to separate the items over the navbar just add a little bit of spacing,
Rest is perfect, and a great job!

**Comment by arpit456jain** [comment]
Ok @adarshvulli  i will do that no problem

**Comment by adarshvulli** [comment]
> Ok @adarshvulli i will do that no problem

and even 
image
add the URL to the home page for the logos! in both the navbars we missed that

**Comment by arpit456jain** [comment]
Ok @adarshvulli 
As soon that colour palete PR gor merge i will resolve these merge conflicts and do these changes

**Comment by arpit456jain** [comment]
making  a new and fresh Pr

**Pull request closed without merging**
