### PR TITLE
Backend for sign up 

### LINKED ISSUE #172: Backend for sign up
Writing the backend for sign up and adding proper validation so that email can be unique

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issue 

Backend for sign up  

Closes: #172 

### Describe the changes you've made

https://user-images.githubusercontent.com/55352601/118346726-14c46a00-b55b-11eb-9f31-5e836905f6ba.mp4

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Additional Info (optional)
Any additional information you want to give

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by arpit456jain** [comment]
@adarshvulli @ankitapuri kindly review this PR . In this PR i had written the code for sign up .
There is one thing left , it would be great if someone else can add some error success message after signup . Rest all is good , its working properly . 
If nobody add this error success message , i will surely add it. no problem to me , i just  wanted to give some issues to other contributors :)

**Comment by arpit456jain** [comment]
https://drive.google.com/file/d/1bs2xKSGcX8yhZu6G_X-TgBB2FRn3gGkA/view?usp=sharing

**Comment by arpit456jain** [comment]
hey @adarshvulli and @ankitapuri please have a look on the video who's link is provided above . I know there is a little bit explicit work is needed to be done in flask but its a one time work once you set up the db then you just have to import and export the sql file

**Comment by arpit456jain** [comment]
Although In Django this is very very easy no tension of sql file , no tension of database and its very flexible also but as you know previously there was a lot of mess in the project lots of css overwriting each other .
So once i clean the code and make a fully working website . i will migrate it into DJango if you say ... :) but it will take some time to complete this website in flask

**Review by adarshvulli — APPROVED** [review]

**Comment by adarshvulli** [comment]
@ankitapuri  this pr is good to be merged

**Pull request merged**
