### PR TITLE
Harshit branch

### PR DESCRIPTION
**Pull request by Harshit850**
Till now CSS part is completed, I will further continue animation if you like the design. Have a look at it and let me know.

### CODE REVIEW

**Comment by ankitapuri** [comment]
@Harshit850 It looks good to me, Just we need to change some colors to match the main page . 
Also , how about adding some moving effects .

**Comment by Harshit850** [comment]
ok i will change the colors as you like and i can also add moving effects with anime.js

**Comment by Harshit850** [comment]
@ankitapuri tell me about the colors or any specific idea about animation.

**Comment by ankitapuri** [comment]
once see the #9 you will get idea about the color scheme.

**Pull request closed without merging**
