### PR TITLE
User can now set custom canvas grid

### LINKED ISSUE #82: Adjust the board size according to the user choice
**Screenshots**

The form should be able to take user input and when we press submit button the canvas takes the size according to the user preference and the need .

### PR DESCRIPTION
**Pull request by athkdev**
## Related Issue 

- Canvas was always set to a default size of 16x16, couldn't be changed by user

Closes: #82

### Describe the changes you've made

I have added changes which now enables to set custom size to the canvas from the landing page

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behavior of your code (Write NA if not)
NA

## Additional Info (optional)
NA

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by rish-singhal — COMMENTED** [review]
@ankitapuri 
Note: The grid size remains the same, it's just that it gets divided into X * Y boxes. 
If this is okay, then we can go ahead and merge.

**Comment by ankitapuri** [comment]
> @ankitapuri
> Note: The grid size remains the same, it's just that it gets divided into X * Y boxes.
> If this is okay, then we can go ahead and merge.

Yeah we wanted the canvas size according to user input.

**Comment by rish-singhal** [comment]
@ankitapuri  Then I guess this is not happening, canvas size remains constant but it gets divided into X * Y boxes. For example, size of canvas for both 1X1 and 2X2 is same (with different box size)

**Comment by athkdev** [comment]
@rish-singhal The design intentionally doesn't change the canvas size (it does change if the dimensions are non-square), because this way we could change the resolution of the cursor (brush size), rather than the actual canvas size.
For eg. a 16x16 and 45x45 would have the same canvas size, the difference is that the 45x45 would be more crisp.

**Review by adarshvulli — APPROVED** [review]

**Review by rish-singhal — APPROVED** [review]

**Review by ankitapuri — APPROVED** [review]

**Pull request merged**
