### PR TITLE
added show password feature in login and signup

### LINKED ISSUE #277: show password feature in login and sign up
show password feature in login and sign up

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issue 

- Info about the related issue 

Closes: #277 

### Describe the changes you've made

Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Additional Info (optional)
Any additional information you want to give

## Checklist:

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by arpit456jain** [comment]
@ankitapuri please review this PR

**Comment by adarshvulli** [comment]
hey @arpit456jain I see the same issue with the show password in my system
image
can you send me a screenshot/video from your side

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/119557851-56a4aa00-bdbe-11eb-8dbf-cf39de510c52.mp4

@adarshvulli  here is the video . I don't know why its behaving weird in your system 
@ankitapuri can you confirm please if it fine in your system or not

**Comment by ankitapuri** [comment]
>  2021-05-26.01-04-17.mp4 
> @adarshvulli here is the video . I don't know why its behaving weird in your system
> @ankitapuri can you confirm please if it fine in your system or not

Its fine in my system @adarshvulli and @arpit456jain

**Pull request merged**
