### PR TITLE
Dark mode in home page with new and responsive toggle button

### LINKED ISSUE #200: Dark mode in home page with new and responsive toggle button
Dark mode in home page with new and responsive toggle button

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issue 

Dark mode in home page with new and responsive toggle button

Closes: #200 

### Describe the changes you've made

I am uploading a video

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by arpit456jain** [comment]
1. In This PR i had added a new toggle button on home page .
2. Its fully responsive
3. i had moved darkmode js to a separate js file for darkmode  named **darkmode.js** since previously its in login.html but now we can included it wherever we need
4. fixed a small bug

since there are so many changes @adarshvulli i request you to review it carefully Although i had checked it from my side and uploading a video also

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/118507746-24ef6b80-b74c-11eb-9659-2b8957c64ede.mp4

**Comment by arpit456jain** [comment]
There was a bug when we run project first time we were by default logged in but now its fixed  :)

**Review by adarshvulli — CHANGES_REQUESTED** [review]
image
Hey @arpit456jain with the recent change I suppose the CSS for the icons has tampered I see the difference in the size of the 2 social icons,! rest all are good and great work, the login is also cool the parameter set is a game changer 👍

**Comment by arpit456jain** [comment]
> image
> Hey @arpit456jain with the recent change I suppose the CSS for the icons has tampered I see the difference in the size of the 2 social icons,! rest all are good and great work, the login is also cool the parameter set is a game changer 👍

@adarshvulli  dont't worry of them i am working on a better our team section than this on a different branch will make a PR soon i created this for a layout purpose . whether its needed or not .
Because previously there was a confusion about testimonial section . that's why i had not make that PR before but now its confirmed that our team section is ok.

So I will try to complete my work asap and will create a PR soon :)

**Comment by arpit456jain** [comment]
ott

**Comment by arpit456jain** [comment]
its fixed @adarshvulli :)

**Review by adarshvulli — APPROVED** [review]

**Comment by adarshvulli** [comment]
@ankitapuri good to be merged

**Pull request merged**
