### PR TITLE
created a forgot password card

### LINKED ISSUE #131: Create a forgot password page
**Screenshots**

### PR DESCRIPTION
**Pull request by gnikita432**
## Related Issue 

-Created a forgot passoword page

Closes: #131 

### Describe the changes you've made

In the login page when user will click on the forgot password link this forgot password page will pop up on the screen
## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code
NA

## Additional Info (optional)
Any additional information you want to give

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by gnikita432** [comment]
image

**Review by avinal — COMMENTED** [review]
Hello @gnikita432, the password card looks quite functional, but can you please change the styling to the one we have on our main page, like solid colors and rounded square buttons. It would look more seamless with the project then.

**Comment by gnikita432** [comment]
@avinal Actully I have created the forgot password page according to the theam of the login page.
image

**Comment by gnikita432** [comment]
Hey, @avinal @ankitapuri If the whole login page theme is not suitable for the site, then I can create a new PR for changing the theme.

**Comment by ankitapuri** [comment]
> @avinal Actully I have created the forgot password page according to the theam of the login page.
> image

actually the borders are not black of login page card , just check once @gnikita432

**Comment by gnikita432** [comment]
Ohh. No, actually that is not a border. Actually, I have created the card like, When a user will click on the forgot password then this card will pop up on the login block and the whole background will go a bit dark when the card will pop up. If you want me to remove it then I can remove it. Or if any other changes are needed then please let me know I will do those changes with this.

**Comment by ankitapuri** [comment]
@avinal  your suggestions on it

**Comment by gnikita432** [comment]
Hey, @ankitapuri

https://user-images.githubusercontent.com/61223163/117777036-d298e100-b259-11eb-9f03-614479f63a81.mp4

The forgot password page works like this. Can you please review it or merge it. It's been more than 18 days since I have made the PR.

**Pull request merged**
