### PR TITLE
Footer of login page #17

### LINKED ISSUE #17: To create a login page for users
It will be divided in 3 parts : 
- header (which will contain the name of the project and toggle button for light n dark mode )
- main body ( where the user will have the option to signup/sign in using the mail address and password )
- footer (mentioning made with love)

### PR DESCRIPTION
**Pull request by shairanshrawat**
## Related Issue 

- Info about the related issue 
- 

Closes: [#17]

### Describe the changes you've made

I have added a footer to the login page that says made with (heart), using HTML, CSS and the heart in it goes up and down in a motion 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behavior of your code (Write NA if not)
NA

## Additional Info (optional)
Added login.html and added the CSS in the pre-existing CSS file

## Checklist:

- [ ] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by ankitapuri** [comment]
there are 2 CSS files why ?

**Comment by shairanshrawat** [comment]
> there are 2 CSS files why ?

sorry for the inconvenience, I have updated have a look

**Comment by ankitapuri** [comment]
Resolve the conflicts once . Just put the body of ur html under the login form html , similarly for css in login.css

**Comment by shairanshrawat** [comment]
> Resolve the conflicts once . Just put the body of ur html under the login form html , similarly for css in login.css

I have updated have a look

**Comment by rish-singhal** [comment]
@shairanshrawat Resolve conflicts.

**Pull request closed without merging**
