### PR TITLE
Adjusted the border-shadow in Dark-mode

### LINKED ISSUE #115: Fixing border of login page
I have adjusted the border a bit. Please let me know if this is the one you were looking for:

Screenshot 2021-04-10 224007

### PR DESCRIPTION
**Pull request by SilverGraph**
## Related Issue 

- The border-shadow in Dark-mode was a bit off.

Closes: #115 

### Describe the changes you've made

Changed the border-shadow in Dark-mode only.

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
`NA`

## Additional Info (optional)
Before:
unknown

After:
Screenshot 2021-04-10 224007

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by rish-singhal** [comment]
seems fine, but the text is not aligned well in Safari. Although, in google chrome it works good!

**Comment by SilverGraph** [comment]
@rish-singhal As far as I know Safari is not available for Windows. Could you help me and tell me how could I see the page so that I could fix it?

**Comment by rish-singhal** [comment]
@SilverGraph [
Screenshot 2021-04-12 at 11 41 04 AM
](url)

~ maybe try using inspect element in chrome, and changing device settings. See if it helps.

**Comment by SilverGraph** [comment]
@rish-singhal I tried to set-up the pixels to macbook size but it's still shows the same.
Screenshot 2021-04-12 131554

**Comment by rish-singhal** [comment]
Ah okay, see if there is any work around otherwise, you can a raise an issue for that. And this PR can be merged.

**Pull request merged**
