### PR TITLE
Adding themes

### LINKED ISSUE #127: Enhancing user input.html page
I would like to add different themes to the web page. I can also enhance the buttons and add hover effect.

### PR DESCRIPTION
**Pull request by CMELAKKIA**
## Related Issue 

- #127 

Closes: #127 
### Describe the changes you've made

Enhanced the website view with the modification of index.html, app.js, style.css

## Type of change

Added skin colors for the website

Example how to mark a checkbox:-
- [x] My code follows the code style of this project.
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
NA

## Checklist:
- [x] My code follows the code style of this project.
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by CMELAKKIA** [comment]
@avinal  @ankitapuri  I have added blue-black color to dim theme.

**Comment by ankitapuri** [comment]
ok I'll review it

**Comment by ankitapuri** [comment]
Can u please resolve the conflicts

**Comment by CMELAKKIA** [comment]
> Can u please resolve the conflicts

Yes, done !!

**Comment by ankitapuri** [comment]
@CMELAKKIA can u please check this , I really can't see any themes

**Comment by CMELAKKIA** [comment]
> @CMELAKKIA can u please check this , I really can't see any themes

image
please click on the settings icon to view the themes and styles. @ankitapuri

**Review by avinal — COMMENTED** [review]
The blue black you added is still too dark, just see the GitHub theme for reference 
image

Your theme 
image

**Comment by CMELAKKIA** [comment]
image
@avinal @ankitapuri   I have set the color code to #696969 (dim gray) .
or if you want it to be darker will you prefer #353535 (darker shade of this gray)

**Comment by ankitapuri** [comment]
> image
> @avinal @ankitapuri I have set the color code to #696969 (dim gray) .
> or if you want it to be darker will you prefer #1E232A (darker shade of this gray)

dark grey would be better

**Comment by CMELAKKIA** [comment]
image
@ankitapuri  I have made the changes.

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/117331120-0d92c180-aeb4-11eb-8805-ac67107a2d8e.mp4

**Comment by arpit456jain** [comment]
@ankitapuri here is the video you asked for

**Comment by ankitapuri** [comment]
> @ankitapuri here is the video you asked for

@CMELAKKIA can u once look into the issue in the video , bcoz on adding up your code there is some problem on the canvas page .

**Comment by CMELAKKIA** [comment]
@ankitapuri  @adarshvulli  I've made the required changes

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/117618649-e37b2100-b18b-11eb-969e-eccdd739ffb9.mp4

Still the issue is there

**Comment by CMELAKKIA** [comment]
Can you create this bug  as separate issue  and work on that ? @arpit456jain

**Comment by arpit456jain** [comment]
> Can you create this bug as separate issue and work on that ? @arpit456jain

Nope. 
I suggest first separate that 1 page into 2 and then this feature can be added to 1st page so that it will not effect the 2nd page

**Comment by arpit456jain** [comment]
hey @CMELAKKIA i have divided that 1 page into two and now they are independent so you can just rebase your branch .and add this feature in user_input.html and make a separate css and js file for it
Just make sure to make a copy of your folder before re-basing otherwise  your work may be lost  so that after rebasing you can add your code easily . If you are facing any problem in rebasing you can simply make a new PR :)

**Comment by CMELAKKIA** [comment]
#190 Created new PR due to major conflicts in rebasing

**Pull request closed without merging**
