### PR TITLE
Added the button

### LINKED ISSUE #96: Create a button
**Screenshots**
Create a button which user can click and get back to the page where he can adjust the size according to the preference . 
 Ref: https://codepen.io/manelroig/pen/rJMVRO

### PR DESCRIPTION
**Pull request by hritikgupta92**
## Related Issue 

Closes: #96

### Describe the changes you've made

Made the following changes-
(i)Created the button using CSS.
(ii) Added the functionality to button s.t on clicking the button it redirects you to main page

## Type of change

What sort of change have you made:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by avinal — COMMENTED** [review]
image

Hello @hritikgupta92, The backbutton is working fine but can you please center the arrows, it seems more to left-top corner.

**Comment by hritikgupta92** [comment]
Ok,I'll do the changes.

**Comment by hritikgupta92** [comment]
@avinal I have done the required changes please check

**Review by avinal — APPROVED** [review]
Changes looks good to me. @ankitapuri please merge it

**Pull request merged**
