### PR TITLE
shifted return button to left just below the dropdown

### LINKED ISSUE #149: Adjusting Return button
**Screenshots**

Shifting the return button to extreme left just below the drop-down menu

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issue 

shift back button to left just below the dropdown

Closes: #149 

### Describe the changes you've made
backbutton

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Additional Info (optional)
Any additional information you want to give

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by arpit456jain** [comment]
@ankitapuri here is the PR kindly review it 

and i have made a home page and uploaded that video to that issue kindly review it too

**Comment by adarshvulli** [comment]
hey @arpit456jain so far great work done. 
image
along with the above change can you even work where on the start screen the so far back option (circle) be hidden.

**Comment by arpit456jain** [comment]
> hey @arpit456jain so far great work done.
> image
> along with the above change can you even work where on the start screen the so far back option (circle) be hidden.

@adarshvulli there is no need for that I had discussed with @ankitapuri to make separate page for entering dimensions and the canvas page because as the more thing are adding in canvas page it is going to be very difficult to maintain all items

I had made a home page it contains a navbar we can give all links to navbar and i can try to put a navbar in both the pages(canvas and before canvas ) then there will be no need of back button  .

That's why no need to worry about that button

**Comment by adarshvulli** [comment]
Okay that's nice ! I wasn't aware of the discussion, but I am glad your working on the canvas ! 
So @ankitapuri this pr can be merged!

**Pull request merged**
