### PR TITLE
Responsiveness in home page

### LINKED ISSUE #178: Responsiveness in home page
**Screenshots**
Current home is not responsive for all screen specially for mobile view . I am working on it to make it responsive 

https://user-images.githubusercontent.com/55352601/118084780-e457c100-b3de-11eb-8a1b-4e0a0b3e0c0c.mp4

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issue 

Responsiveness in home page and route for home page

Closes: #178 

### Describe the changes you've made

https://user-images.githubusercontent.com/55352601/118091791-de66dd80-b3e8-11eb-9f27-371ef69d1e0f.mp4

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by arpit456jain** [comment]
@ankitapuri kindly review my PR your whole website is ready now

**Comment by arpit456jain** [comment]
And Don't worry for footer 
i have a idea for it

**Comment by avinal** [comment]
Hello @arpit456jain, will you be adding more commits to this?

**Comment by arpit456jain** [comment]
no its complete

> Hello @arpit456jain, will you be adding more commits to this?

**Comment by arpit456jain** [comment]
@avinal @ankitapuri any changes required?

**Comment by arpit456jain** [comment]
@adarshvulli can you please review this PR .

**Comment by adarshvulli** [comment]
@arpit456jain  due to the latest additions i think the conflicts raised once have a look! once resolved  @ankitapuri  this is also good to be merged

**Comment by arpit456jain** [comment]
> @arpit456jain due to the latest additions i think the conflicts raised once have a look! once resolved @ankitapuri this is also good to be merged

Ok I will resolve them no problem i am just waiting for login PR to be merged

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/118372231-39a5f500-b5ce-11eb-9ef3-398fc48cf2f4.mp4

**Comment by arpit456jain** [comment]
hey @adarshvulli see now the website is almost completed :) 
@ankitapuri you can merge it :)

**Review by ankitapuri — APPROVED** [review]

**Pull request merged**
