### PR TITLE
added responsiveness in the Index page

### LINKED ISSUE #130: Index page is not responsive
**Screenshots**
image
I want to work on making the index page responsive  under gssoc

### PR DESCRIPTION
**Pull request by gnikita432**
## Related Issue 

- added responsiveness in the Index page and also fixed the title(the image and title were not vertically in center) I made them vertically centered too.

Closes: #130 

### Describe the changes you've made

Give a clear description what modifications you have made
image

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [] Code style update (formatting, local variables)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code
NA
## Additional Info (optional)
Any additional information you want to give

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by adarshvulli — CHANGES_REQUESTED** [review]
image
Hey, @gnikita432 great work so far! but here the canvas has to be fixed but I can see the buttons and other sections are moving where the canvas is not fixed. and I can even see the scroll bar when it is being responsive can we come up with a solution where we hide the scroll bar like  (overflow = hidden;) or u can use the WebKit-scroll bar to try to implement with these.

**Comment by gnikita432** [comment]
Sure, I will make the changes.

**Comment by gnikita432** [comment]
Hey, I will fix the scrollbar issue but can you please elaborate the canvas issue. Currently the canvas is fixed and not the other buttons or section therefore the other sections are moving. So you want to to move canvas also?
https://user-images.githubusercontent.com/61223163/115491957-84a64400-a27e-11eb-9e62-d90433403bb2.mp4

**Review by avinal — COMMENTED** [review]
I think other than PC, people will use this application on tablets and iPads, Here is a screenshot from iPad.
image
We can easily see that the back button is on the canvas. It should be below the canvas. 

Rest everything is working as expected I think.

**Comment by gnikita432** [comment]
Ohh Okay I will fix this. Thank you

**Comment by gnikita432** [comment]
I have made the changes. please review

image

**Review by avinal — APPROVED** [review]
Looks fine now 👍🏼

**Review by adarshvulli — APPROVED** [review]
looks good! @ankitapuri  this can be merged

**Review by rish-singhal — APPROVED** [review]

**Comment by gnikita432** [comment]
@ankitapuri Thank you for merging the pull request. Can you please add gssoc and level tag.

**Comment by ankitapuri** [comment]
> @ankitapuri Thank you for merging the pull request. Can you please add gssoc and level tag.

sorry for missing it

**Pull request merged**
