### PR TITLE
Added UI for color palette

### LINKED ISSUE #112: New Feature: Choice of Colour to Draw with
I would like to give the user the option to pick a color with which they can draw on the canvas, so that they are not limited to using only black. A color input can be added for this beside the canvas element

### PR DESCRIPTION
**Pull request by N-Shar-ma**
## Partially fixes #112  

- The issue was to add a functional color palette. This PR creates the UI for the color palette, to which functionality can be easily added

### Describe the changes you've made

- added a palette element with display grid
- added 12 basic colors to it
- given the colors a selected class which can be toggled via javascript to show which is selected at any instant

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
NA

## Checklist:

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly whereever it was hard to understand.
- [X] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by avinal — COMMENTED** [review]
The addition looks good, but I am no longer able to scroll the page, also it is fine it this is not scrolling but the canvas is shifting itself downward and the last row of pixel becomes inaccesible.

**Comment by N-Shar-ma** [comment]
@avinal Thanks for pointing out the bug, I have fixed it now

**Review by ankitapuri — APPROVED** [review]

**Comment by ankitapuri** [comment]
Its perfect now

**Comment by N-Shar-ma** [comment]
> Its perfect now

Thank you!

**Pull request merged**
