### PR TITLE
Fixes #30

### LINKED ISSUE #30: Add the labels in the Readme.md
Add labels in the Readme displaying 
- No of contributors 
- Issues opened 
- Issues closed 
- PRs open
- PRs closed
- Repo Size
- Built By developers 
- Built with Love

### PR DESCRIPTION
**Pull request by SHAIMA-HAQUE**
#30 Closes: #[30]

Added the labels 

- No of contributors

- Issues opened

- Issues closed

- PRs open

- PRs closed

- Repo Size

- Built By developers

- Built with Love

Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code
N/A

## Additional Info (optional)
Any additional information you want to give

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by ankitapuri** [comment]
Ur PR has conflicts with the file . Please check it

**Comment by ankitapuri** [comment]
@SHAIMA-HAQUE please fix this issue by the end of the day and also add Built By developers and Built with Love just below the other labels . 
If u won't be able to complete by the end of the day , this PR will be closed

**Comment by SHAIMA-HAQUE** [comment]
Please check if it is alright now

**Review by adarshvulli — CHANGES_REQUESTED** [review]
can you add the tag line just below the project heading which is now present at line 37 ,rest all are perfect mam!

**Comment by SHAIMA-HAQUE** [comment]
Could you please check now ,sir
I am new to this, so I wanted to ask that I just had to commit the change to my branch ,right?

**Review by adarshvulli — APPROVED** [review]
this is good to be merged @ankitapuri

**Comment by adarshvulli** [comment]
> Could you please check now ,sir
> I am new to this, so I wanted to ask that I just had to commit the change to my branch ,right?

yes mam!

**Comment by avinal** [comment]
Hello @SHAIMA-HAQUE, although the PR is complete as Adash said, but I would like you to squash your commits into a single commit. It's pretty simple:
```
git checkout 30-update-readme

# here we want to squash 3 commits
git reset --soft HEAD~3

# add changes (BTW they are already staged)
git stage -A

# Add  new commit message
git commit -m "Added labels in Readme.md"

# force push
git push -f origin 30-update-readme
```
No problem if you can't as we can squash from our side too, it is just a learning opportunity if you don't know already. Also, remember to put only as many commits as the number of absolute changes.

**Comment by SHAIMA-HAQUE** [comment]
@avinal Thank you so much for letting me know.

**Pull request merged**
