### PR TITLE
fixed the  bug in dark mode

### LINKED ISSUE #181: Bug In Dark Mode
It reset on refresh . when dark mode is activated it should be in dark mode even after refresh 

https://user-images.githubusercontent.com/55352601/118227237-d28d2100-b4a5-11eb-9184-5fc41a09e00b.mp4

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issue 

It reset on refresh . when dark mode is activated it should be in dark mode even after refresh

https://user-images.githubusercontent.com/55352601/118228312-98248380-b4a7-11eb-997f-332e1d2d0a2f.mp4

Closes: #181 

### Describe the changes you've made

I write a js for making it perfect

https://user-images.githubusercontent.com/55352601/118228502-edf92b80-b4a7-11eb-9300-18aa20805880.mp4

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by arpit456jain** [comment]
@adarshvulli please review the PR

**Comment by adarshvulli** [comment]
hey @arpit456jain  the drank mode  for the forgot password card isn't working
image
rest all are perfect!

**Comment by arpit456jain** [comment]
> hey @arpit456jain the drank mode for the forgot password card isn't working
> image
> rest all are perfect!

@adarshvulli there is no css present for it . Should i add it under this issue .?
 
I think this issue for bug and i can create separate issue for that so that anyone can work on it since @ankitapuri wants other people to contribute

**Comment by arpit456jain** [comment]
If you say i can do it i have no problem just confirm once
@adarshvulli @ankitapuri  :)

**Comment by adarshvulli** [comment]
> > hey @arpit456jain the drank mode for the forgot password card isn't working
> > image
> > rest all are perfect!
> 
> @adarshvulli there is no css present for it . Should i add it under this issue .?
> 
> I think this issue for bug and i can create separate issue for that so that anyone can work on it since @ankitapuri wants other people to contribute

So if that is the case, lets wait ! i will get back to you regarding the same !

**Comment by arpit456jain** [comment]
Yeah no problem to me :)

**Pull request merged**
