### PR TITLE
Implement darkmode for Forget Password

### PR DESCRIPTION
**Pull request by rupal11**
Closes: #[issue number that will be closed through this PR]
#183 

### Describe the changes you've made

Changed drakmode.js, login.html and login.css

## Type of change

What sort of change have you made:

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
NA

## Checklist:

- [ x] My code follows the guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by rish-singhal** [comment]
Screenshot 2021-05-20 at 6 43 45 PM
Screenshot 2021-05-20 at 6 43 54 PMo
Screenshot 2021-05-20 at 6 43 52 PM
Screenshot 2021-05-20 at 6 43 48 PM


Hi, @rupal11 so this is what I am getting when I click on dark mode button repeatedly, instead of switching between dark mode and light mode. Also, the text is not readable in one mode.

**Comment by rupal11** [comment]
It is working fine in my system.





https://user-images.githubusercontent.com/60324778/119014240-646cc080-b9b5-11eb-8606-ca7550ede5c6.mp4



What can be the error?

**Comment by rish-singhal** [comment]
well that is wierd, I will try this out again in ubuntu. I was getting above thing in MacOS, Chrome

**Comment by rish-singhal** [comment]
well, with linux too it seems the UI have issues. I guess the application is not working uniform across all the UI and OS combination.

Screenshot_2021-05-20 Login Signup Form


Have you tried using it on some other OS or browser?

**Review by rish-singhal — CHANGES_REQUESTED** [review]
Try out different browsers

**Comment by rupal11** [comment]
**Edge**

edge1
edg2
edge3
edge4


**Firefox**

firefox
firefox2
firefox3
firefox4

**Comment by rupal11** [comment]
Do I have to try any other browser?

**Comment by rupal11** [comment]
I have not pulled the current changes(migrating to django) because it will remove the changes that I made.

**Comment by rish-singhal** [comment]
No this seems good, I guess we will need to revamp CSS for this: But again that is unrelated to the dark mode--, this thing needs to be done first -- then we can update the dark mode problem for forget password.

Also, currently your implementation does not account for round edges (as it can be seen from your working screenshots for Chrome, Windows)

**Comment by rupal11** [comment]
Ok

For round edges, since the css will be restructured, I will correct it afterwards.

**Pull request closed without merging**
