### PR TITLE
Box-shadow added

### PR DESCRIPTION
**Pull request by Aarti002**
i have added shadow effect please review and let me know if something is missing, @ankitapuri 
Screenshot (141)

### CODE REVIEW

**Comment by ankitapuri** [comment]
Only the loader keeps on loading ! No visible changes even the user input board doesn't gets displayed . 
Please look into this

**Comment by Aarti002** [comment]
but everything is perfectly working in my system @ankitapuri 
see i have also shared a screenshot

**Comment by ankitapuri** [comment]
> but everything is perfectly working in my system @ankitapuri
> see i have also shared a screenshot

I'll send the video regarding the same

**Comment by Aarti002** [comment]
okay thank u so much @ankitapuri

**Comment by ankitapuri** [comment]
https://drive.google.com/file/d/1lOV_YKEE7b1Lc-aNw3XHwWOssB54PL4i/view?usp=sharing
check this

**Comment by Aarti002** [comment]
how to resolve this , can you help? @ankitapuri

**Comment by ankitapuri** [comment]
> how to resolve this , can you help? @ankitapuri

check your code once . In JS it might have stuck in an infinite loop

**Comment by Aarti002** [comment]
but i have made very minimal changes i don't feel there is problem in JS file still will look into it again

**Comment by arpit456jain** [comment]
@Aarti002 please make a new and fresh PR 
@ankitapuri please close this this PR

**Pull request closed without merging**
