### PR TITLE
Art Gallery Section on Home page

### LINKED ISSUE #271: Art Gallery Section on Home page
Art Gallery Section on Home page

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issue 

Art Gallery Section on Home page

Closes: #271 

### Describe the changes you've made

https://user-images.githubusercontent.com/55352601/119341546-8a45de00-bcb1-11eb-9b5d-39ace767866a.mp4

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Additional Info (optional)
Any additional information you want to give

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by arpit456jain** [comment]
I know my art is not good these are the sample images

**Comment by arpit456jain** [comment]
@ankitapuri please review this PR

**Comment by adarshvulli** [comment]
image
@arpit456jain  over the dark mode this is the issue rest all are perfect!

**Comment by arpit456jain** [comment]
> image
> @arpit456jain over the dark mode this is the issue rest all are perfect!

Ok @adarshvulli  i will check it
Kindly review the PR for 404 error handling code. 
Since it's related to backed PA will not merged it until its approved

**Comment by arpit456jain** [comment]
@adarshvulli  #264

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/119364219-4d3b1500-bccc-11eb-8dfb-76e5295e0286.mp4

@adarshvulli its fine in my system

**Comment by arpit456jain** [comment]
i added some more margin and padding now 

https://user-images.githubusercontent.com/55352601/119364652-bc186e00-bccc-11eb-83f3-a4c241b1507d.mp4

**Comment by adarshvulli** [comment]
>  2021-05-24.20-11-44.mp4 
> @adarshvulli its fine in my system

let me check again

**Comment by arpit456jain** [comment]
@ankitapuri are you facing the same problem in dark mode

**Comment by ankitapuri** [comment]
image

**Comment by arpit456jain** [comment]
Cool..
Then i think its good to be merged

**Review by ankitapuri — APPROVED** [review]

**Pull request merged**
