### PR TITLE
added a navbar in canvas.html and moved download button in navbar

### LINKED ISSUE #208: Adding Navbar in canvas.html And moving Download button in navbar
Adding Navbar in canvas.html And moving all buttons in navbar

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issue 

added a navbar in canvas.html and moved download button in navbar

Closes: #208 

### Describe the changes you've made

https://user-images.githubusercontent.com/55352601/118591688-3c693b80-b7c2-11eb-9683-4c48018588d3.mp4

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Additional Info (optional)
Any additional information you want to give

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by arpit456jain** [comment]
@adarshvulli please review this carefully . 
I had not moved that drop down of tools in navbar because if i do that there will be a lots of changes which will be hard to review

For moving that drop down to navbar , first i have to clean the code and remove un necessary CSS  and drop some comments that which code is written for which part

**Comment by adarshvulli** [comment]
> @adarshvulli please review this carefully .
> I had not moved that drop down of tools in navbar because if i do that there will be a lots of changes which will be hard to review
> 
> For moving that drop down to navbar , first i have to clean the code and remove un necessary CSS and drop some comments that which code is written for which part

yeah, @arpit456jain  good work I don't think login and /logout is needed in the navbar of the paint section rest all are good! 
image

**Comment by arpit456jain** [comment]
Ok @adarshvulli i will remove it

**Comment by arpit456jain** [comment]
Done @adarshvulli

**Review by adarshvulli — APPROVED** [review]

**Comment by adarshvulli** [comment]
@ankitapuri good to be merged

**Pull request merged**
