### PR TITLE
backEnd for Contact us 

### LINKED ISSUE #241: backEnd for Contact us
backEnd for Contact us

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issue 

backEnd for Contact us 

Closes: #241 

### Describe the changes you've made

Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Additional Info (optional)
Any additional information you want to give

## Checklist:

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by arpit456jain** [comment]
@adarshvulli please review this

**Comment by arpit456jain** [comment]
Dont't forget to run command 
py.exe .\manage.py makemigrations home

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/119091155-42f9ec00-ba2a-11eb-81bd-65fbb26c2799.mp4

**Comment by arpit456jain** [comment]
I had also check it from my side its working fine. video uploaded above
It gave me an csrf token error once  but when refresh it it works fine

**Comment by adarshvulli** [comment]
So far, great job, @arpit456jain  congratulations on that 🎉 ,
so remove the previous contact us part over the main page and add the new one and change the respective URL even in the navbar! Try to complete everything related to the contact page in this PR!

**Comment by arpit456jain** [comment]
> So far, great job, @arpit456jain congratulations on that 🎉 ,
> so remove the previous contact us part over the main page and add the new one and change the respective URL even in the navbar! Try to complete everything related to the contact page in this PR!

Sure

**Comment by arpit456jain** [comment]
@adarshvulli done

**Review by adarshvulli — APPROVED** [review]

**Pull request merged**
