### PR TITLE
separate New Contact Us page front end

### LINKED ISSUE #239: A separate New Contact Us page
A separate New Contact Us page

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issue 

-separate New Contact Us page front end

Closes: #239 

### Describe the changes you've made

Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Additional Info (optional)
Any additional information you want to give

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by arpit456jain** [comment]
contact

**Comment by arpit456jain** [comment]
@ankitapuri please merge this

**Comment by ankitapuri** [comment]
image
 These are some unnecessary comments which needs to be deleted

**Comment by arpit456jain** [comment]
> image
> These are some unnecessary comments which needs to be deleted

@ankitapuri that will be automatically removed when render with django that's not a problem

**Comment by arpit456jain** [comment]
@ankitapuri I had commented out that csrf token and removed that **message.txt 4kb** that was actually unnecessary

**Comment by arpit456jain** [comment]
sl

**Comment by ankitapuri** [comment]
Great @arpit456jain 🎉

**Pull request merged**
