### PR TITLE
Add Darkmode to ContactUs page

### PR DESCRIPTION
**Pull request by rupal11**
Closes: #[issue number that will be closed through this PR]
#330

### Describe the changes you've made

Changed the color scheme of contact us page and added darkmode.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Na

## Checklist:

- [x ] My code follows the guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by adarshvulli** [comment]
image
hey @rupal11, everything is good. I was hoping you could reduce the contrast or may choose a liter version of the pink or change it  to a brown color

**Comment by rupal11** [comment]
1.


2.



Which of the two did you like the most?

**Comment by adarshvulli** [comment]
> 
> 
> 
> 
> 
> Which of the two did you like the most?

Let's go with 2 @ankitapuri your  views

**Comment by rupal11** [comment]
Should I apply the change?

**Comment by ankitapuri** [comment]
> Should I apply the change?

yes go ahead

**Comment by rupal11** [comment]
Done.

**Review by adarshvulli — APPROVED** [review]

**Pull request merged**
