### PR TITLE
Gsoc'21 Fix the bug in changing modes

### LINKED ISSUE #84: Bug In Changing Light mode to Dark Mode in Login/Signup Page
Light Mode is ok but when i switched to dark mode It creates a problem because i am not able to see the content written in form because it is of black color.

It should change to White color when dark mode is activated and change to black color when light mode is activated I am attaching a video for better understanding my issue

https://user-images.githubusercontent.com/55352601/111904519-67a70700-8a6d-11eb-96b4-6ce28cb45a5e.mp4

 Please assign me this issue as i am a gssoc'21 participant and i would love to work on it.

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issue 

There was a bug in changing modes like when user switched to dark mode
Light Mode is ok but when i switched to dark mode It creates a problem because i am not able to see the content written in form because it is of black color.
I had solved this issue and added a form tag which was previously missing 
Closes: #84 

### Describe the changes you've made

It should change to White color when dark mode is activated and change to black color when light mode is activated so i added some css to it.
 I am attaching a video for better understanding my improved code

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Additional Info (optional)
Any additional information you want to give

## Checklist:

- [ x] My code follows the guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.

I hope Its fine. please add label of gsoc'21 before merging.

### CODE REVIEW

**Comment by arpit456jain** [comment]
@ankitapuri mam please check this I hope It is fine

**Review by adarshvulli — CHANGES_REQUESTED** [review]
I really appreciate your effort and work sir! but the size of the light button has to be still reduced and the build has to be in the middle of the main circle. this seems odd now. and try reducing the contrast in the dark mode cause the form isn't visible in the dark color

**Comment by arpit456jain** [comment]
ok sir let me try..

**Comment by arpit456jain** [comment]
Hello @adarshvulli sir I had tried to do all the changes you mentioned above
Changes Done.
1. Light bulb is now in the middle (in perfect position)
2. The background color is changed a little bit in dark-mode , now its visible perfectly.
3. Currently i am working on reducing the size of light bulb in phone view but it's very complicated to me as there are a lot of CSS mixing up taking for now i had maintain some margin so that it doesn't look bad

I am attaching a video for better understanding the changes i had done ...Please Review it 

https://user-images.githubusercontent.com/55352601/111948323-fd41a580-8b04-11eb-9b68-2477c6d93ede.mp4


**Note: Please ignore the size of light bulb for now i am working on it if i success i will make a PR in future as i created this issue related to the bug in changing modes **

**Comment by arpit456jain** [comment]
Sir kindly merge this PR then I will Fork the Latest Code and start Working on Reducing size of light bulb because I had also created a issue(#83) about Responsiveness yesterday . So i can also work on this issue under that Issue(#83) if it is assign to me.

**Comment by arpit456jain** [comment]
Sir Please add labels of gssoc'21 before merging.

**Review by ankitapuri — APPROVED** [review]

**Comment by arpit456jain** [comment]
@ankitapuri mam sorry to disturb you , but I didn't get any score for it and This issue and PR is not showing in my gssco  profile.
Can you please check it what went wrong so I can take care of it in future.

**Comment by ankitapuri** [comment]
> @ankitapuri mam sorry to disturb you , but I didn't get any score for it and This issue and PR is not showing in my gssco profile.
> Can you please check it what went wrong so I can take care of it in future.

I have asked the organizers once . will update u about it

**Pull request merged**
