### PR TITLE
home page

### LINKED ISSUE #68: Adding a Homepage
**Screenshots**
I would like to add a homepage to this website that describes the purpose and a few other details about this website.
we can also add a navbar that can contain links which can be routed.
(Prefer to use React.js)

### PR DESCRIPTION
**Pull request by SnehaVeerakumar**
## #68 

- Adding a home page for the website. 

Closes: #68 

### Describe the changes you've made

As I had no sufficient informations, I could use general terms for footer details. I have added a navigation bar to navigate through various pages. Homepage.html will act as an entry point. "paint" option in navigation bar navigates to index.html.
If I am provided with informations for about section,contact us, I am excited to work on those parts in this same PR.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
NA

## Additional Info (optional)
Preloader could not be loaded for the whole page. I need to sort it out. Please level down the issue to "level1" if you accept this PR. As I have not worked on other details due to lack of information, this cannot be awarded with 45 points. But I would like to work if the reviewers suggest it.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by SnehaVeerakumar** [comment]
Screenshot (1217)
Screenshot (1218)
Screenshot (1219)

**Comment by adarshvulli** [comment]
Hello @SnehaVeerakumar, first of this is great work congratulations on that, So, there are few changes which  when done, would be a great and perfect page for the  project 
1. I think we don't need the address part. Instead, we can add some testimonials 
2. add our logo  in the place of the project name in the navbar section 
3 .  made the navbar transparent
I hope I am clear. If not I am open to the discussion over the server  :)

**Comment by adarshvulli** [comment]
hey @SnehaVeerakumar any updates?

**Comment by SnehaVeerakumar** [comment]
> hey @SnehaVeerakumar any updates?

Give me some time to figure out your recent changes. It is totally new now and I lost my works in few git commands. I will update it by today evening.
Thank you for your patience.

**Comment by SnehaVeerakumar** [comment]
@adarshvulli It will be helpful if you update starter guide for your flask application.

**Comment by SnehaVeerakumar** [comment]
@adarshvulli  I don't know flask. What do I do now ?

**Comment by adarshvulli** [comment]
hey, @SnehaVeerakumar  yes we are working on that! i will update you with the details for the same or think for the alternative, thank you for the work so far, I will get back to you regarding the same in a while.

**Comment by arpit456jain** [comment]
> @adarshvulli I don't know flask. What do I do now ?

@SnehaVeerakumar No need to worry just move your home.html to another folder then pull the master branch and again place that home.html to root folder i will make a route for that in flask 

Just make sure that home.html should be independent put all css and js related to that page in home.html and don't edit anything in in css placed in static folder.

**Comment by arpit456jain** [comment]
And don't forget to do the changes mentors asked 🙂

**Comment by adarshvulli** [comment]
> > @adarshvulli I don't know flask. What do I do now ?
> 
> @SnehaVeerakumar No need to worry just move your home.html to another folder then pull the master branch and again place that home.html to root folder i will make a route for that in flask
> 
> Just make sure that home.html should be independent put all css and js related to that page in home.html and don't edit anything in in css placed in static folder.

@SnehaVeerakumar this solution would be better for the above concern ! in the mean while we shall edit the staters guide

**Comment by SnehaVeerakumar** [comment]
> > @adarshvulli I don't know flask. What do I do now ?
> 
> @SnehaVeerakumar No need to worry just move your home.html to another folder then pull the master branch and again place that home.html to root folder i will make a route for that in flask
> 
> Just make sure that home.html should be independent put all css and js related to that page in home.html and don't edit anything in in css placed in static folder.

Independent? Isn't that supposed to have an option that redirects to painting page?
Will you take care of those stuffs !?
If yes, I am okay with it

**Comment by SnehaVeerakumar** [comment]
> > > @adarshvulli I don't know flask. What do I do now ?
> > 
> > 
> > @SnehaVeerakumar No need to worry just move your home.html to another folder then pull the master branch and again place that home.html to root folder i will make a route for that in flask
> > Just make sure that home.html should be independent put all css and js related to that page in home.html and don't edit anything in in css placed in static folder.
> 
> @SnehaVeerakumar this solution would be better for the above concern ! in the mean while we shall edit the staters guide

Can I make another PR please.  I cannot rebase and commit any changes due to conflicts

**Comment by arpit456jain** [comment]
> > > @adarshvulli I don't know flask. What do I do now ?
> > 
> > 
> > @SnehaVeerakumar No need to worry just move your home.html to another folder then pull the master branch and again place that home.html to root folder i will make a route for that in flask
> > Just make sure that home.html should be independent put all css and js related to that page in home.html and don't edit anything in in css placed in static folder.
> 
> Independent? Isn't that supposed to have an option that redirects to painting page?
> Will you take care of those stuffs !?
> If yes, I am okay with it

Yes i will take care of it 👍

**Comment by arpit456jain** [comment]
> > > @adarshvulli I don't know flask. What do I do now ?
> > 
> > 
> > @SnehaVeerakumar No need to worry just move your home.html to another folder then pull the master branch and again place that home.html to root folder i will make a route for that in flask
> > Just make sure that home.html should be independent put all css and js related to that page in home.html and don't edit anything in in css placed in static folder.
> 
> @SnehaVeerakumar this solution would be better for the above concern ! in the mean while we shall edit the staters guide

@adarshvulli i have opened a issue for adding some documentation for flask kindly Assign me that issue and allow me to make a PR

**Comment by adarshvulli** [comment]
> > > > @adarshvulli I don't know flask. What do I do now ?
> > > 
> > > 
> > > @SnehaVeerakumar No need to worry just move your home.html to another folder then pull the master branch and again place that home.html to root folder i will make a route for that in flask
> > > Just make sure that home.html should be independent put all css and js related to that page in home.html and don't edit anything in in css placed in static folder.
> > 
> > 
> > @SnehaVeerakumar this solution would be better for the above concern ! in the mean while we shall edit the staters guide
> 
> Can I make another PR please. I cannot rebase and commit any changes due to conflicts

yes go ahead I will be closing this PR!

**Comment by adarshvulli** [comment]
> > > > @adarshvulli I don't know flask. What do I do now ?
> > > 
> > > 
> > > @SnehaVeerakumar No need to worry just move your home.html to another folder then pull the master branch and again place that home.html to root folder i will make a route for that in flask
> > > Just make sure that home.html should be independent put all css and js related to that page in home.html and don't edit anything in in css placed in static folder.
> > 
> > 
> > @SnehaVeerakumar this solution would be better for the above concern ! in the mean while we shall edit the staters guide
> 
> @adarshvulli i have opened a issue for adding some documentation for flask kindly Assign me that issue and allow me to make a PR

Okay sure then!

**Comment by SnehaVeerakumar** [comment]
@adarshvulli  Below screenshots are the outputs. My personal opinion is not to go with transparent nav bar. I have attanched transparent nav bar image and my preferred nav bar. Please have a look at this. Also there are 2 options for logo, transparent backgroud and your default logo image available.

Screenshot (1223)

Screenshot (1227)



Screenshot (1225)

**Comment by adarshvulli** [comment]
The first design looks more good  @SnehaVeerakumar

**Comment by SnehaVeerakumar** [comment]
> The first design looks more good @SnehaVeerakumar

New PR has been added. Thank you for your patience and guidance.

**Pull request closed without merging**
