### PR TITLE
Adding 404 page

### PR DESCRIPTION
**Pull request by rupal11**
Closes: #[issue number that will be closed through this PR]
#255 

Give a clear description what modifications you have made

Added a 404 page

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x ] My code follows the guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [x ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by rupal11** [comment]
The page is not fully complete. I will complete it very soon.

**Comment by arpit456jain** [comment]
@rupal11 you just have to add 1 html page only but just see your PR once your PR changing 7 files : |
Why are you making PR from main branch of your repo. you have to make a new branch and on that branch do the changes not on main branch

**Comment by rupal11** [comment]
I am not much familiar with branching(practical). I have tried but it was very confusing. I want to become more familiar with it and want to try first it in my repo.

**Comment by arpit456jain** [comment]
> I am not much familiar with branching(practical). I have tried but it was very confusing. I want to become more familiar with it and want to try first it in my repo.

Just follow these steps.
1 move your 404 html page to somewhere.
2 delete the repo and fork it again.
3 delete the copy on local system and git clone again.
4 run git checkout -b 404page
5 copy your 404 html page to template folder .
6 add commit and  make PR

@adarshvulli @ankitapuri please correct me if i wrong somewhere

**Comment by rupal11** [comment]
Ok but can I do it tomorrow. I am really not feeling well.

**Comment by ankitapuri** [comment]
> > I am not much familiar with branching(practical). I have tried but it was very confusing. I want to become more familiar with it and want to try first it in my repo.
> 
> Just follow these steps.
> 1 move your 404 html page to somewhere.
> 2 delete the repo and fork it again.
> 3 delete the copy on local system and git clone again.
> 4 run git checkout -b 404page
> 5 copy your 404 html page to template folder .
> 6 add commit and make PR
> 
> @adarshvulli @ankitapuri please correct me if i wrong somewhere

Yes these are right

**Pull request closed without merging**
